version: '2'
services:
  helpdesk_postgres:
    image: postgres:9.6.8-alpine
    container_name: helpdesk_postgres
    restart: always
    volumes:
      - helpdesk_postgres:/var/lib/postgresql/data
      - $PWD/config:/tmp/config
      - $PWD/scripts/dockerCreateDatabase.sh:/docker-entrypoint-initdb.d/dockerCreateDatabase.sh
      - $PWD/postgresql.sql:/tmp/postgresql.sql
    environment:
      - POSTGRES_PASSWORD=123456

  helpdesk_web:
    build: docker
    container_name: helpdesk_web
    restart: always
    ports:
      - 8000:8000
    links:
      - helpdesk_postgres
    volumes:
      - $PWD:/app
    working_dir: /app
    command: sh -c "npm install; npm start"

volumes:
  helpdesk_postgres:
    driver: local